railspro/config/routes.rb
Rails.application.routes.draw do

  resources :missions
  root 'missions#index'		#配置首页路由
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

railspro/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railspro/app/models/mission.rb
class Mission < ApplicationRecord
end

railspro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

railspro/app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]

  # GET /missions
  # GET /missions.json
  def index
    @missions = Mission.all
  end

  # GET /missions/1
  # GET /missions/1.json
  def show
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to missions_url, notice: 'Mission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:index, :title, :detail)
    end
end

railspro/app/helpers/application_helper.rb
module ApplicationHelper
end

railspro/app/helpers/missions_helper.rb
module MissionsHelper
end

railspro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railspro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

railspro/app/views/missions/_form.html.haml
= simple_form_for(@mission) do |f|
  = f.error_notification

  .form-inputs
    = f.input :index,label:'编号',placeholder:'编号',error:'integer',input_html:{maxlength:2},hint:'请填入整数'
    = f.input :title,placeholder:'请输入标题'
    = f.input :detail,input_html:{placeholder:'请输入内容',style:'border:1px solid red'},required:true
    = f.input :detail,as: :radio_buttons,collection:["同意","不同意"],input_html:{selected:'selected'}
  .form-actions
    = f.button :submit,value:'保存'

railspro/app/views/missions/edit.html.haml
%h1 Editing mission

= render 'form'

= link_to 'Show', @mission
\|
= link_to 'Back', missions_path

railspro/app/views/missions/index.html.haml
/ %h1{:style => "border-bottom:1px solid black;"} 任务列表 
%h1{:style => "border-bottom:1px solid black;text-align:center"} 任务列表 
= link_to '+新增任务', new_mission_path
%p
%table
  %thead
    %tr
      %th 编号
      %th 标题
      %th 内容
      %th 操作
      %th 
      %th

  %tbody
    - @missions.each do |mission|
      %tr
        %td= mission.index
        %td= mission.title
        %td= mission.detail
        %td= link_to '查看', mission, target:'_blank', value: '查看'
        %td= link_to '编辑', edit_mission_path(mission)
        %td= link_to '删除', mission, method: :delete, data: { confirm: 'Are you sure?' }

%br

railspro/app/views/missions/new.html.haml
%h1 New mission

= render 'form'

= link_to 'Back', missions_path

railspro/app/views/missions/show.html.haml
%p#notice= notice

%p
  %b Index:
  = @mission.index
%p
  %b Title:
  = @mission.title
%p
  %b Detail:
  = @mission.detail

= link_to 'Edit', edit_mission_path(@mission)
\|
= link_to 'Back', missions_path